services:
  frontend:
    image: ${FRONTEND_IMAGE_NAME}
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx-logs:/var/log/nginx
    networks:
      - app-network

  backend:
    image: ${BACKEND_IMAGE_NAME}
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    container_name: backend
    networks:
      - app-network
    environment:
      - PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge