name: Deploy to Server

on: 
  workflow_call:

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          source: "./docker-compose.yaml"
          target: "~/.deploy/${{github.repository}}/"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            export FRONTEND_IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/github-actions-frontend:${{ github.sha }}
            export BACKEND_IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/github-actions-backend:${{ github.sha }}
            cd ~/.deploy/${{github.repository}}/
            docker compose up -d --pull always