name: DevSecOps Deployment Pipeline

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:
  code-quality-scan:
    uses: ./.github/workflows/code-quality.yml

  secrets-leak-scan:
    uses: ./.github/workflows/secrets-scan.yml

  code-dependency-scan:
    uses: ./.github/workflows/dependency-scan.yml

  docker-lint-check:
    uses: ./.github/workflows/docker-linter.yml

  docker-build-push-scan:
    needs: [code-quality-scan, secrets-leak-scan, code-dependency-scan, docker-lint-check]
    uses: ./.github/workflows/build-push-scan.yml

  deploy-to-server:
    needs: docker-build-push-scan
    uses: ./.github/workflows/deploy-to-server.yml