name: Greet-on-Github-Actions

on:
  # run on any push on main branch
  push:
    branches: [main]
    paths:
      - '.github/workflows/greet-users.yml'
  # can be also run manually 
  workflow_dispatch: 
    
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to user
        run: echo "Hello $USER"
        
  details:
    runs-on: ubuntu-latest
    needs: greet
    steps:
      - name: Print OS Details
        run: cat /etc/os-release
      - name: Print kernal details
        run: uname -a

  date-time:
    runs-on: ubuntu-latest
    needs: details
    steps:
      - name: Print uptime 
        run: uptime
      - name: Print date-time
        run: date

  all-process:
    runs-on: ubuntu-latest
    needs: date-time
    steps: 
      - name: print all process
        run: ps -ef
