name:  GitHub Matrix Strategy HandsOn

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # false - run all jobs even if one fails, true - stop all jobs if one fails
      fail-fast: false 
      matrix:
        # runs on each os
        os: [ubuntu-latest, macos-latest, windows-latest] 
        # runs on each node version
        node-version: [18.x, 20.x, 22.x, 24.x] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run the script 
        run: node print-version.js